### ISSUE TITLE
python2 doesn't seem to be available from msys2 anymore?

### ISSUE THREAD

**Issue by plicease** [StrawberryPerl/build-extlibs#2]
When trying to install python2 I got this error:

```
ContainerAdministrator@a6ae4b2a4597 MINGW64 /c/spbuild/build-extlibs
# pacman -Sy --noconfirm python2
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 ucrt64 is up to date
 clang32 is up to date
 clang64 is up to date
 msys is up to date
error: target not found: python2
```

I found these instructions for installing python2:

https://github.com/msys2/MSYS2-packages/issues/2334#issuecomment-776281337

Though I didn't get to the point where I was actually using python in the build process so I have 0% confidence that is the right thing.  (in particular that is the mingw-w64-x86_64 build of python2 and not the msys2 one I think?).

I also don't know what the build process needs python2 for or if it will now work with python3.  Ideally of course python2 shouldn't be used if python3 will work.

**Comment by shawnlaffan** [comment]
I don't think python is needed but it's installed as part of the docker image under the https://github.com/StrawberryPerl/spbuild instructions.  

The readme needs to be updated.

**Comment by shawnlaffan** [comment]
This should be obviated by recent changes to the instructions under #33
