### ISSUE TITLE
build.sh cmd.exe call sometimes stays in the cmd shell

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/build-extlibs#23]
Perhaps it is just my system, but it seems this call can sometimes stay in the cmd shell (or more correctly it starts a shell and waits for input).

https://github.com/StrawberryPerl/build-extlibs/blob/5323db5d6313a9584ed62511544de62adfa0538f/build.sh#L252

Exiting from the shell keeps the build process moving but obviously means the process cannot be run non-interactively.  

Is the cmd call needed?  It seems to be removing the readonly flag, which can be done using ```chmod -R u+w *```.  The line has been in the build system for more than 8 years so might be present purely for historical reasons.

**Comment by genio** [comment]
I think it's worth pulling it out if you can remove the flag without going into CMD.
