### ISSUE TITLE
build.sh - are the patched package diffs needed?

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/build-extlibs#25]
The second of these two lines in build.sh runs a recursive diff on any package dir that has had patches applied.  The original dir is then deleted.
https://github.com/StrawberryPerl/build-extlibs/blob/5323db5d6313a9584ed62511544de62adfa0538f/build.sh#L261-L263

I can see this is useful in development but it really slows things down.  For example, about two hours of the 5034 set is spent running these processes (it takes a particularly long time for the db package, which is about 230MB).  The diffs are also redundant when rerunning builds from scratch when one knows the patching works.  

I have not found anywhere that uses the diff results but it is a simple matter to wrap them in a conditional so they only trigger when an env var is set, e.g. ```$RETAIN_PATCHED_PKG_DIFFS```.  A dummy ```$OUT/$PACK.diff``` file can be created to be on the safe side.

Let me know if you'd like a PR.

**Comment by genio** [comment]
I don't _think_ that's necessary. A PR would be great.

**Comment by shawnlaffan** [comment]
PR merged, closing issue
