### ISSUE TITLE
Instructions specify 483

### ISSUE THREAD

**Issue by plicease** [StrawberryPerl/build-extlibs#3]
The README here specifies 483 as the gcc toolchain, but I think 830 is actually what we want for recent build?  Some sort of indication of which toolchains should be used for which versions of Perl?

**Comment by shawnlaffan** [comment]
These scripts might not be needed now the whole thing is run under docker, although that's documented in the readme for https://github.com/StrawberryPerl/spbuild

This readme should probably be updated to note that.

**Comment by shawnlaffan** [comment]
This should be obviated by recent changes to the instructions under #33
