### ISSUE TITLE
build script - update argument handling

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/build-extlibs#37]
Parts of the system assume the dllsuffix is one or two underscores when it is not passed.  This can lead to issues when reusing build artefacts as the extraction code assumes the underscores if no suffix is passed (e.g. #36).  

Some means to differentiate not passed from passed would be handy as I have not found a good way yet.  Alternately a getopts approach could be tried.  
https://www.baeldung.com/linux/bash-parse-command-line-arguments

**Comment by shawnlaffan** [comment]
Alternately the script could default to the underscores if the second arg is blank or null.  If the user wants no dllsuffix then they can pass "none".  That would be simpler to implement.

e.g. these will default to ```__``` on 64 bit systems:
```
./build.sh 5034
./build.sh 5034 ""
```

This will set dllsuffix to "":
```
./build.sh 5034 none
```

**Comment by genio** [comment]
Let me just put this out there... do we _need_ to worry about 32-bit any longer?

**Comment by shawnlaffan** [comment]
I think not but maybe there are still some uses out there.  Certainly there is no reason 32 bit should hold up a release of 64 bit.

**Comment by shawnlaffan** [comment]
PR merged, closing issue.  

The 32 bit question should probably be raised on the perl-dist-strawberry issue tracker?
