### ISSUE TITLE
cfitsio 3.8 passes the build, and an update for 4.0.0

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/build-extlibs#6]
Opening a separate issue, per comment https://github.com/StrawberryPerl/build-extlibs/issues/4#issuecomment-1262603189

cfitsio 3.8 seems to pass the build process.  The fail in the cmake configure stage is perhaps not an issue.  

Attempting to build cfitsio 4.0.0 results in configure failures as CMake will not build in the source dir.  However, updating build.sh to use the sequence below seems to work (apologies for not submitting a PR).  

```bash
# ----------------------------------------------------------------------------
cfitsio-*)
cd $WRKDIR/$PACK
mkdir _build
cd _build
xxrun cmake -G "MinGW Makefiles" -DWITH_ZLIB=system -DWITH_SSL=bundled -DCMAKE_INSTALL_PREFIX=$OUT -DCMAKE_MAKE_PROGRAM=
gmake ..
#xxrun make  DLLSUFFIX=$DLLSUFFIX PREFIX=$OUT install
xxrun mingw32-make DLLSUFFIX=$DLLSUFFIX install
cd ..
;;
```

Edit: Although the invocation seems not to be appending ```$DLLSUFFIX```.

Edit 2: But 4.1.0 also builds.

**Comment by shawnlaffan** [comment]
It also appears that most (all?) of the dependent modules on CPAN have been moved across to use [Alien::CFITSIO](https://metacpan.org/pod/Alien::CFITSIO).  If so then does Strawberry Perl need to provide it?

@djerius can perhaps shed more light on what uses CFITSIO.

**Comment by djerius** [comment]
I can't imagine anything using the cfitsio library directly outside of the Perl CFITSIO module, which now uses Alien::CFITSIO, so I don't think it's necessary to bundle cfitsio with Strawberry Perl.

The real question is whether Alien::CFITSIO compiles under Strawberry Perl.  It uses the autotool files that cfitsio ships with, rather than cmake ones.

**Comment by shawnlaffan** [comment]
Thanks @djerius 

Alien::CFITSIO compiles and passes tests with Strawberry Perl 5.32 and 5.28.  Same for Astro::FITS::CFITSIO with the alien.

**Comment by djerius** [comment]
Excellent news.  Hopefully Strawberry Perl will be available to run as a GitHub CI (or whatever they call it these days).

**Comment by shawnlaffan** [comment]
We have been distributing Strawberry Perl 5.36 and 5.38 without CFITSIO.  It would seem the Alien approach is doing its job.  

I'll close the issue now.
